spring:
  profiles:
    active: local
  web:
    locale: ko_KR
config:
  restTemplate:
    timeout: 10000
    maxConnTotal: 100
    maxConnPerRoute: 50
---
server:
  port: 8002
spring:
  config:
    activate:
      on-profile: local
config:
  kakao:
    url: http://dapi.kakao.com
    api-key: KakaoAK 5ee6a8608905a09709f24f7941701bf6
  naver:
    url: https://openapi.naver.com
    client-id: xBXFUoSBYboasKPaoA9g
    client-secret: ZH8FVv2xPq

---
spring:
  config:
    activate:
      on-profile: dev

